#pragma once

#define BAUD_RATE 115200

#define LED_PIN 32
#define BUZZER_PIN 27
#define BUTTON_PIN 14

#define LORA_SCK_GPIO 18
#define LORA_MISO_GPIO 19
#define LORA_MOSI_GPIO 23
#define LORA_CS_GPIO 5
#define LORA_RST_GPIO 13
#define LORA_DIO0_GPIO 26

#define LORA_DIO0_WAKEUP_PIN GPIO_NUM_26